services:
  essentia-db:
    image: mysql:lts
    container_name: essentia-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3308:3306"
    volumes:
      - essentia-db:/var/lib/mysql
    networks:
      - essentia-network

  essentia-app:
    image: node:bookworm
    container_name: essentia-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: ["node", "/app/backend/dist/index.js"]
    networks:
      - essentia-network
    depends_on:
      - essentia-db

networks:
  essentia-network:
    driver: bridge

volumes:
  essentia-db:
    driver: local
